pipelines:
  mag-api-model-artifact-build:
    group: LGI-MAG-COMMON
    locking: on
    label_template: "${upstream[:8]}-${COUNT}"
    tracking_tool:
      link: "https://orionjira.atlassian.net/browse/${ID}"
      regex: "MAG--(\\d+)"
    environment_variables:
      cucumberenv: test
    materials:
      upstream:
        git: git@gitlab.piksel.com:liberty/mag-api-model.git
        destination: app
        blacklist:
          - pipeline.gocd.yaml
        shallow_clone: true
      parent:
        pipeline: mag-parent-pom-artifact-build
        stage: deploy
    stages:
      - build:
          clean_workspace: true
          jobs:
            mvn_build:
              tasks:
               - exec:
                   working_directory: app
                   command: decache
                   arguments:
                    - /var/go/.m2/repository
               - exec:
                   working_directory: app
                   command: mvn
                   arguments:
                    - clean
                    - package
      - deploy:
          clean_workspace: false
          jobs:
            mvn_build:
              tasks:
               - exec:
                   working_directory: app
                   command: mvn
                   arguments:
                    - deploy
               - exec:
                   working_directory: app
                   command: cache
                   arguments:
                    - /var/go/.m2/repository
  mag-api-model-artifact-release:
    group: LGI-MAG-RELEASE
    locking: on
    label_template: "${upstream[:8]}-${COUNT}"
    tracking_tool:
      link: "https://orionjira.atlassian.net/browse/${ID}"
      regex: "MAG--(\\d+)"
    materials:
      upstream:
        git: git@gitlab.piksel.com:liberty/mag-api-model.git
        destination: app
        blacklist:
          - pipeline.gocd.yaml
          - Makefile
        shallow_clone: true
    stages:
      - release:
          approval:
            type: manual
            roles:
              - metadata
          jobs:
            mvn_prepare_perform:
              tasks:
                - exec:
                   working_directory: app
                   command: make
                   arguments:
                     - "update-parent-versions"
                - exec:
                   working_directory: app
                   command: make
                   arguments:
                     - "release"
