pipelines:
  mag-ingest-app-tva-artifact-build:
    group: LGI-MAG-INGEST
    locking: on
    label_template: "${upstream[:8]}-${COUNT}"
    tracking_tool:
      link: "https://orionjira.atlassian.net/browse/${ID}"
      regex: "MAG--(\\d+)"
    environment_variables:
      cucumberenv: test
    materials:
      upstream:
        git: git@gitlab.piksel.com:liberty/mag-ingest-app-tva.git
        destination: app
        blacklist:
          - pipeline.gocd.yaml
        shallow_clone: true
      parent:
        pipeline: mag-parent-pom-artifact-build
        stage: deploy
      ingest-profile-tva:
        pipeline: mag-ingest-profile-tva-artifact-build
        stage: deploy
    stages:
      - build:
          clean_workspace: true
          jobs:
            mvn_build:
              elastic_profile_id: small
              tasks:
               - exec:
                   working_directory: app
                   command: decache
                   arguments:
                    - /var/go/.m2/repository
               - exec:
                   working_directory: app
                   command: mvn
                   arguments:
                    - clean
                    - package
               - exec:
                   working_directory: app
                   command: cache
                   arguments:
                    - /var/go/.m2/repository
      - deploy:
          clean_workspace: false
          jobs:
            mvn_build:
              elastic_profile_id: small
              tasks:
               - exec:
                   working_directory: app
                   command: decache
                   arguments:
                    - /var/go/.m2/repository
               - exec:
                   working_directory: app
                   command: mvn
                   arguments:
                    - deploy
               - exec:
                   working_directory: app
                   command: cache
                   arguments:
                    - /var/go/.m2/repository
  mag-ingest-app-tva-artifact-release-labs:
    group: LGI-LABS-RELEASE
    locking: on
    label_template: "${upstream[:8]}-${COUNT}"
    tracking_tool:
      link: "https://orionjira.atlassian.net/browse/${ID}"
      regex: "MAG--(\\d+)"
    environment_variables:
      dest: labs
    materials:
      upstream:
        git: git@gitlab.piksel.com:liberty/mag-ingest-app-tva.git
        destination: app
        blacklist:
          - pipeline.gocd.yaml
        shallow_clone: true
      cfg:
        git: git@gitlab.piksel.com:prd-S3-authenticated-request-configuration/piksel-lgilabs-assets.git
        destination: cfg
        blacklist:
          - README.md
        shallow_clone: true
      ingest-profile-tva:
        pipeline: mag-ingest-app-tva-artifact-build
        stage: deploy
    stages:
      - build:
          clean_workspace: true
          jobs:
            upload_artifact:
              elastic_profile_id: small
              tasks:
               - exec:
                   working_directory: app
                   command: decache
                   arguments:
                    - /var/go/.m2/repository
               - exec:
                   working_directory: app
                   command: mvn
                   arguments:
                    - package
               - exec:
                   working_directory: app
                   command: make
                   arguments:
                    - deploy
                    - DEST=labs
               - exec:
                   working_directory: app
                   command: cache
                   arguments:
                    - /var/go/.m2/repository
  mag-ingest-container-build:
    group: LGI-MAG-INGEST
    locking: on
    label_template: "${upstream[:8]}-${COUNT}"
    tracking_tool:
      link: "https://orionjira.atlassian.net/browse/${ID}"
      regex: "MAG--(\\d+)"
    materials:
      upstream:
        git: git@gitlab.piksel.com:liberty/mag-ingest-container.git
        destination: app
        blacklist:
          - pipeline.gocd.yaml
        shallow_clone: true
    stages:
      - build:
          clean_workspace: true
          jobs:
            build_container:
              elastic_profile_id: small
              tasks:
               - exec:
                   working_directory: app
                   command: make
                   arguments:
                    - up
 mag-ingest-app-tva-artifact-release:
       group: LGI-MAG-RELEASE
       locking: on
       label_template: "${upstream[:8]}-${COUNT}"
       tracking_tool:
         link: "https://orionjira.atlassian.net/browse/${ID}"
         regex: "MAG--(\\d+)"
       materials:
         upstream:
           git: git@gitlab.piksel.com:liberty/mag-ingest-app-tva.git
           destination: app
           blacklist:
             - pipeline.gocd.yaml
           shallow_clone: true
     stages:
       - release:
           approval:
             type: manual
             roles:
             - metadata
           jobs:
             mvn_prepare_perform:
               elastic_profile_id: small
               tasks:
                 - exec:
                    working_directory: app
                    command: make
                    arguments:
                       - update-parent-versions
                 - exec:
                     working_directory: app
                     command: mvn
                     arguments:
                            - -B
                            - release:prepare
                            - release:perform
